name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Setup uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca
        with:
          python-version: 3.13
          enable-cache: true
      - name: build package
        run: uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
        with:
          repository-url: https://test.pypi.org/legacy/
